name: Hugo

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Push back
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Build /public files" -a
          git push

      - name: Deploy
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.ALIYUN_CADDY_WEBHOOK_URL }}
          data: "{\"ref\": \"${{ github.ref }}\"}"
